### PR TITLE
Names to make zombotron happy

### PR DESCRIPTION
**Pull request by mohammedarts**

### CODE REVIEW

**Comment by xombotron** [comment]
snake_case

**Comment by mohammedarts** [comment]
> snake_case

i forgot the name

**Comment by Zombotron134567** [comment]
> > snake_case
> 
> i forgot the name

it isn't snake_case

**Comment by xombotron** [comment]
god, I sound like a discord mod

**Comment by mohammedarts** [comment]
> god, I sound like a discord mod

we know

**Pull request merged**
